app/main/forms.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
	search = StringField('search', validators=[DataRequired()])

app/main/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint

main = Blueprint('main', __name__, template_folder="templates/clean", static_url_path='',
				 static_folder='templates/clean/static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views, errors

app/main/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import render_template, redirect, request, current_app, url_for, g
from . import main
from ..models import Article, Tag, Category, TagSpaces
from .forms import SearchForm


@main.before_request
def before_request():
    g.tags = Tag.query.all()
    g.categorys = Category.query.all()
    g.recent_articles = Article.query.order_by(Article.timestamp.desc()).limit(5).all()
    articles = Article.query.order_by(Article.timestamp.desc()).all()
    time_tag = []
    for a in articles:
        if a.timestamp.strftime('%Y-%m') not in time_tag:
            time_tag.append(a.timestamp.strftime('%Y-%m'))
    g.time_tag = time_tag
    g.search_form = SearchForm(prefix='search')


@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    articles = Article.query.order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('index.html', articles=articles)

@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('about.html')


@main.route('/article/<pid>', methods=['GET', 'POST'])
def article(pid):
    article = Article.query.get(int(pid))

    return render_template('article.html', article=article)


@main.route('/tag/<t>', methods=['GET', 'POST'])
def tag(t):
    page = request.args.get('page', 1, type=int)
    tag = Tag.query.filter_by(name=t).first()
    articles = Article.query.join(TagSpaces, TagSpaces.tag_id == tag.id).filter(TagSpaces.article_id == Article.id). \
        order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('tag.html', articles=articles, tag=tag)


@main.route('/category/<c>', methods=['GET', 'POST'])
def category(c):
    page = request.args.get('page', 1, type=int)
    cty = Category.query.filter_by(name=c).first()
    articles = Article.query.filter_by(cty=cty).order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('category.html', articles=articles, category=cty)


@main.route('/archives/<time_tag>', methods=['GET', 'POST'])
def archives(time_tag):
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter(Article.timestamp.startswith(time_tag)). \
        order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('archives.html', articles=articles, time_tag=time_tag)


@main.route('/search/', methods=['GET', 'POST'])
def search():
    if not g.search_form.validate_on_submit():
        return redirect(url_for('.index'))

    return redirect(url_for('.search_results', query=g.search_form.search.data.strip()))


@main.route('/search_results/<query>', methods=['GET', 'POST'])
def search_results(query):
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter(Article.body.like('%%%s%%' % query)).order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)
    return render_template('search_result.html', articles=articles, query=query)

app/main/templates/clean/common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come
        *after* these tags -->
        <meta name="description" content="{% block desc %}编程！我们是认真的！{% endblock %}">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('main.static', filename='images/favicon.ico')}}">

        <title>{% block title %}藕丝空间{% endblock %}</title>
        {% block css %}
            <!-- Bootstrap core CSS -->
            <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
                  rel="stylesheet">
            <!-- Custom fonts for this template -->
            <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css"
                  rel="stylesheet" type="text/css">
            <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
                  rel='stylesheet' type='text/css'>
            <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,
            400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet'
                  type='text/css'>

            <!-- Custom styles for this template -->
            <link href="{{ url_for('main.static', filename='css/clean-blog.css') }}" rel="stylesheet">
            <link rel="stylesheet" type="text/css"
                  href="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.css" />
        {% endblock %}
    </head>

    <body data-spy="scroll" data-target="#sidebar" data-offset="20">
        {% include 'common/header.html' %}
        {% block content %}

        {% endblock %}
        {% include 'common/footer.html' %}
        {% block js %}
            <!-- Bootstrap core JavaScript -->
            <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js">
            </script>
            <!-- 加载KaTeX js 文件 -->
            <script type="text/javascript" src="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.js">
            </script>
            <!-- Custom scripts for this template -->
            <script src="{{ url_for('main.static', filename='js/clean-blog.min.js') }}"></script>
            {{ moment.include_moment(local_js=url_for('admin.static', filename='js/moment-with-locales.js')) }}
            {{ moment.lang('zh-cn') }}
            <script type="text/javascript">
                $("tex.tex-inline").each(
                    function(i, domElem) {
                        katex.render(domElem.innerText, domElem, {displayMode: false});
                    });
                $("tex.tex-block").each(
                    function(i, domElem) {
                        katex.render(domElem.innerText, domElem, {displayMode: true});
                    });
            </script>
        {% endblock %}
    </body>
</html>

app/main/templates/clean/common/footer.html
<hr>
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://weibo.com/gbshi">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a target="_blank"
                           href="http://wpa.qq.com/msgrd?v=3&uin=27614108&site=qq&menu=yes"
                           title="点击这里给我发消息">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-qq fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-weixin fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/eastossifrage">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                </ul>
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <span class="copyright text-muted">Copyright &copy; 藕丝空间 2014-2018</span>
                    </li>
                    <li class="list-inline-item">
                        <span class="copyright text-muted">
                            <a target="_blank" href="http://www.miitbeian.gov.cn/publish/query/indexFirst.action">
                                豫ICP备14004317号-1
                            </a>
                        </span>
                    </li>
                    <li class="list-inline-item">
                        <span class="copyright text-muted">
                            <a target="_blank" href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41070202000426">
                                <img src="{{ url_for('.static', filename='images/beian.png') }}">
                                豫公安网安备 41070202000426号
                            </a>
                        </span>
                    </li>
                    <li class="list-inline-item">
                        <span class="copyright text-muted">本网站基于
                            <a target="_blank" href="https://github.com/eastossifrage/pyblog">pyblog</a>
                            项目</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/main/templates/clean/common/header.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('.static', filename='images/favicon.png') }}"
                 class="rounded-circle" alt="logo" style="width:40px;">
            藕丝空间
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
        菜单
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">主页</a>
                </li>
                    <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.about') }}">关于</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.index') }}">管理</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/main/templates/clean/common/search.html
<div class="container" style="margin-top: 40px">
    <div class="row">
        <div class="col-lg-6 col-md-8 mx-auto">
            <div class="form-group">
                <form method="post" role="form" action="{{ url_for('main.search') }}">
                    {{ g.search_form.hidden_tag() }}
                    <div class="input-group">
                        {{ g.search_form.search(class="form-control", placeholder="全站搜索", required="") }}
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="fa fa-search fa-2x"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>