app/main/forms.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
	search = StringField('search', validators=[DataRequired()])

app/main/__init__.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'


from flask import Blueprint

main = Blueprint('main', __name__, template_folder="templates/clean", static_url_path='',
				 static_folder='templates/clean/static')

# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views, errors

app/main/views.py
# -*- coding:utf-8 -*-
__author__ = '东方鹗'

from flask import render_template, redirect, request, current_app, url_for, g
from . import main
from ..models import Article, Tag, Category, TagSpaces
from .forms import SearchForm


@main.before_request
def before_request():
    g.tags = Tag.query.all()
    g.categorys = Category.query.all()
    g.recent_articles = Article.query.order_by(Article.timestamp.desc()).limit(5).all()
    articles = Article.query.order_by(Article.timestamp.desc()).all()
    time_tag = []
    for a in articles:
        if a.timestamp.strftime('%Y-%m') not in time_tag:
            time_tag.append(a.timestamp.strftime('%Y-%m'))
    g.time_tag = time_tag
    g.search_form = SearchForm(prefix='search')


@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    articles = Article.query.order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('index.html', articles=articles)

@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('about.html')


@main.route('/article/<pid>', methods=['GET', 'POST'])
def article(pid):
    article = Article.query.get(int(pid))

    return render_template('article.html', article=article)


@main.route('/tag/<t>', methods=['GET', 'POST'])
def tag(t):
    page = request.args.get('page', 1, type=int)
    tag = Tag.query.filter_by(name=t).first()
    articles = Article.query.join(TagSpaces, TagSpaces.tag_id == tag.id).filter(TagSpaces.article_id == Article.id). \
        order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('tag.html', articles=articles, tag=tag)


@main.route('/category/<c>', methods=['GET', 'POST'])
def category(c):
    page = request.args.get('page', 1, type=int)
    cty = Category.query.filter_by(name=c).first()
    articles = Article.query.filter_by(cty=cty).order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('category.html', articles=articles, category=cty)


@main.route('/archives/<time_tag>', methods=['GET', 'POST'])
def archives(time_tag):
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter(Article.timestamp.startswith(time_tag)). \
        order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)

    return render_template('archives.html', articles=articles, time_tag=time_tag)


@main.route('/search/', methods=['GET', 'POST'])
def search():
    if not g.search_form.validate_on_submit():
        return redirect(url_for('.index'))

    return redirect(url_for('.search_results', query=g.search_form.search.data.strip()))


@main.route('/search_results/<query>', methods=['GET', 'POST'])
def search_results(query):
    page = request.args.get('page', 1, type=int)
    articles = Article.query.filter(Article.body.like('%%%s%%' % query)).order_by(Article.timestamp.desc()). \
        paginate(page, per_page=current_app.config['OUSI_POSTS_PER_PAGE'], error_out=False)
    return render_template('search_result.html', articles=articles, query=query)

app/main/templates/default/common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="{% block desc %}编程！我们是认真的！{% endblock %}">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('main.static', filename='images/favicon.ico')}}">

        <title>{% block title %}藕丝空间{% endblock %}</title>
        {% block css %}
            <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
            <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
            <!-- KaTeX js主题文件 -->
            <link rel="stylesheet" type="text/css"
                  href="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.css" />
            <!-- 个性化主题文件 -->
            <link href="{{ url_for('main.static', filename='css/monokai.css')}}" rel="stylesheet">
            <link href="{{ url_for('main.static', filename='css/offcanvas.css')}}" rel="stylesheet">
            <!-- font-awesome 主题文件 -->
            <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css"
                  rel="stylesheet">
        {% endblock %}

        {% block js %}
            <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
            <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
            <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
            <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <!-- 加载KaTeX js 文件 -->
            <script type="text/javascript" src="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.js">
            </script>

            <!-- 个性化 js 文件 -->
            <script src="{{ url_for('main.static', filename='js/offcanvas.js')}}"></script>
            {{ moment.include_moment(local_js=url_for('admin.static', filename='js/moment-with-locales.js')) }}
            {{ moment.lang('zh-cn') }}
            <script type="text/javascript">
                $("tex.tex-inline").each(
                    function(i, domElem) {
                        katex.render(domElem.innerText, domElem, {displayMode: false});
                    });
                $("tex.tex-block").each(
                    function(i, domElem) {
                        katex.render(domElem.innerText, domElem, {displayMode: true});
                    });
            </script>
        {% endblock %}
    </head>

    <body>
        {% include 'common/header.html' %}
        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right">
                <div class="col-xs-12 col-sm-9">
                    <p class="pull-right visible-xs">
                        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">导航</button>
                    </p>
                    <div class="row">
                        {% block content %}
                        {% endblock %}
                    </div><!--/row-->
                </div><!--/.col-xs-12.col-sm-9-->
                {% include 'common/sidebar.html' %}
            </div><!--/row-->
            {% include 'common/footer.html' %}
        </div><!--/.container-->
    </body>
</html>

app/main/templates/default/common/footer.html
<hr>

<footer>
    <div class="col-xs-12">
        <div class="col-xs -12 col-sm-4">
            <p>Powered by <a href="http://www.os373.cn">Pyblog</a></p>
            <p><a href="{{ url_for('admin.index') }}">管理页面</a></p>
        </div>
        <div class="col-xs -12 col-sm-4">
            <p><a href="mailto:xxxxxxxxxxxxxx@gmail.com"><i class="glyphicon glyphicon-envelope"></i> xxxxxxxxxxx@gmail.com </a></p>
            <p><a href="http://www.miibeian.gov.cn/" target="_blank">豫ICP备xxxxxxxxxxxxx号</a></p>
        </div>
        <div class="col-xs -12 col-sm-4">
            <p class="pull-right"><a href="#">回到顶部</a></p>
        </div>
    </div>
</footer>

app/main/templates/default/common/header.html
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <span>
                    <img style="width: 24px; height: 24px" alt="藕丝空间" src="{{ url_for('main.static', filename='images/favicon.png')}}">
                    藕丝空间
                </span>
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#about">关于</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->

app/main/templates/default/common/search.html
<ul class="nav nav-pills">
    <li role="presentation" class="col-xs-12">
        <h3>搜索</h3>
    </li>
    <li role="presentation" class="col-xs-12">
        <form method="post" role="form" action="{{ url_for('main.search') }}">
            {{ g.search_form.hidden_tag() }}
            <div class="input-group">
                {{ g.search_form.search(class="form-control", placeholder="搜索") }}
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
            </div>
        </form>
    </li>
</ul>

app/main/templates/default/common/sidebar.html
<div class="col-xs-6 col-sm-3 sidebar-offcanvas small" id="sidebar">
    {% include 'common/search.html' %}
    <ul class="nav nav-pills">
        <li role="presentation" class="col-xs-12">
            <h3>分类目录</h3>
            <br>
        </li>
        {% for category in g.categorys %}
            <li role="presentation" class="col-xs-12">
                <p><i class="glyphicon glyphicon-hand-right"></i><a href="{{ url_for('main.category', c=category.name) }}"> {{ category.name }}</a></p>
            </li>
        {% endfor %}
    </ul>
    <ul class="nav nav-pills">
        <li role="presentation" class="col-lg-12">
            <h3>文件归档</h3>
            <br>
        </li>
        {% for tg in g.time_tag %}
            <li role="presentation" class="col-lg-12">
                <p><i class="glyphicon glyphicon-hand-right"></i><a href="{{ url_for('main.archives', time_tag=tg) }}"> {{ tg }}</a></p>
            </li>
        {% endfor %}
    </ul>
    <ul class="nav nav-pills">
        <li role="presentation" class="col-lg-12">
            <h3>近期文章</h3>
            <br>
        </li>
        {% for article in g.recent_articles %}
            <li role="presentation" class="col-lg-12">
                <p><i class="glyphicon glyphicon-hand-right"></i><a href="{{ url_for('main.article', pid=article.id) }}"> {{ article.title|title }}</a></p>
            </li>
        {% endfor %}
    </ul>
    <ul class="nav nav-pills">
        <li role="presentation" class="col-lg-12">
            <h3>标签</h3>
            <br>
        </li>
        <li role="presentation" class="col-lg-12">
            {% for tag in g.tags %}
                <span class="label"><a href="{{ url_for('main.tag', t=tag.name) }}">{{ tag.name }}</a></span>
            {% endfor %}
        </li>
    </ul>
    <ul class="nav nav-pills">
        <li role="presentation" class="col-lg-12">
            <h3>简介</h3>
            <br>
        </li>
        <li>
            <p>喜欢markdown，爱上藕丝空间。</p>
        </li>
    </ul>
</div><!--/.sidebar-offcanvas-->